### ISSUE TITLE
'isClosed' does not detect closed polygons

### ISSUE THREAD

**Issue by robertkovacs** [HarryStevens/geometric#12]
In version 2.2.1 'isClosed' has a simple implementation: `return polygon[0] === polygon[polygon.length - 1];` which does not work as comparing arrays with '===' gives always 'false', ([10, 0] === [10, 0] returns 'false') therefore this implementation cannot really detect closed polygons.

Something like 

```
function isClosed(polygon) {
    let last = polygon.length - 1;
    for (let i = 0; i < polygon[0].length; i++) {
      if (polygon[0][i] !== polygon[last][i]) {
        return false;
      }
    }
    return true;
}
```

worked for me (I am not fluent in Javascript, so there might be a more elegant implementation).

Tested in Safari Version 13.1 (15609.1.20.111.8).

**Comment by HarryStevens** [comment]
Thanks for pointing this out. Fixed.
