### ISSUE TITLE
Missing "Super" Beginner Documentation : How to use this lib ?

### ISSUE THREAD

**Issue by german-wings** [HarryStevens/geometric#15]
Hello, I am not very used to javascript , can anyone point me out how to actually draw lines and polygons that would be visible to me on screen ? I mean to say how this lib would interact with the html elements ? , I don't know how to do it , and there will always be someone like me who want to use this lib but don't know how to set it up. Request the maintainers of the lib to add some super beginner steps so the lines and polygons object created by this "geometric" lib will show up on the screen.

Thanks.

**Comment by HarryStevens** [comment]
Geometric.js is only intended for geometric calculations and is agnostic about what you choose to do with the results of those calculations. That said, nearly every function in the documentation is accompanied by a link to an example. The examples show not just how to use the library for geometric calculations, but also how to draw shapes to the screen.

**Comment by german-wings** [comment]
Mmmm , perhaps I must have skipped something , I will look again the whole Documentation , If you have a link that could help me get started and help me draw the shapes on screen let me know please , Thanks Have a good day

**Comment by HarryStevens** [comment]
> If you have a link that could help me get started and help me draw the shapes on screen let me know please 

Please see my [comment above](https://github.com/HarryStevens/geometric/issues/15#issuecomment-656235294), which links to some methods of drawing shapes to the screen.

You can also click on the Example link next to each method in this repository's README.

![image](https://user-images.githubusercontent.com/6527267/87068352-6be30b00-c1e3-11ea-802a-02371aff10c3.png)
