### ISSUE TITLE
Feature Request: Add polygonScale for scaleX and scaleY independently 

### ISSUE THREAD

**Issue by modermo** [HarryStevens/geometric#17]
Great library.

I think it would be useful to be able to calculate vertices based on axis independent scales (X or Y), as opposed to just a general scale (X and Y). 

Perhaps something to the tune of:

```
export function polygonScaleX(polygon, scaleX, origin){
   ...etc
}

export function polygonScaleY(polygon, scaleY, origin){
   ...etc
}
```

**Comment by HarryStevens** [comment]
All set. Appreciate the suggestion.

**Comment by modermo** [comment]
Thanks for that!
