### ISSUE TITLE
Bug in polygonIntersectsPolygon()

### ISSUE THREAD

**Issue by DarkBitz** [HarryStevens/geometric#29]
Package version: 2.2.8

Hi, it seems you have a bug in `polygonIntersectsPolygon()` . I have tested this with these arguments:
Polygon A)
```
[
  [3, 3],
  [3, 4],
  [4, 4],
  [4, 3]
]
```
Polygon B)
```
[
  [1, 1],
  [1, 4],
  [2, 4],
  [2, 2],
  [5, 2],
  [5, 4],
  [6, 4],
  [6, 1]
]
```
The first polygon is a simple rectangle. The second is an upside down U. The rectangle is in the opening of U but it never intersects the polygon.

The method incorrectly returns true.

cc @HarryStevens

**Comment by HarryStevens** [comment]
Thanks for this. It looks like I introduced an error in v2.2 because it returns false in v2.1. I am investing the issue, but in the meantime, you should use v2.1, which you can find here: https://cdn.jsdelivr.net/npm/geometric@2.1.1/build/geometric.min.js

**Comment by HarryStevens** [comment]
@DarkBitz This is now fixed. I had allowed lineIntersectsLine to get too complicated, so I simplified its logic and everything fell into place. Thank you again for alerting me to it.
