### ISSUE TITLE
Zones and intersection

### ISSUE THREAD

**Issue by svk-man** [HarryStevens/geometric#39]
![image](https://user-images.githubusercontent.com/17108861/208332651-9283af4d-99a4-4736-b2c7-caf2f31d7eac.png)

Good afternoon!

I need to draw three polygons - outer and two inner ones. They can be edited.

All three polygons form zones. I marked them - 1, 2, 3.

I need to be able to switch between zones and look for the intersection of each of the zones with a moving point, for example, the mouse cursor.

Can you please tell me if your library will help me?

**Comment by HarryStevens** [comment]
Hi @svk-man. Yes, you can use [geometric.pointInPolygon](https://github.com/harrystevens/geometric#pointInPolygon) for this.
For example:
```js
const center = [200, 200];

// Polygons ordered from smallest to largest.
const polygonA = [[center[0] - 50, center[1] - 50], [center[0] - 50, center[1] + 50], [center[0] + 50, center[1] + 50], [center[0] + 50, center[1] - 50];
const polygonB = [[center[0] - 100, center[1] - 100], [center[0] - 100, center[1] + 100], [center[0] + 100, center[1] + 100], [center[0] + 100, center[1] - 100];
const polygonC = [[center[0] - 200, center[1] - 200], [center[0] - 200, center[1] + 200], [center[0] + 200, center[1] + 200], [center[0] + 200, center[1] - 200];

// An array of your polygons
const polygons = [polygonA, polygonB, polygonC];

// The polygon your point is inside of
let foundPolygon = [];

// Loop through the polygons
for (let i = 0, l = polygons.length; i < l; i++) {
  const polygon = polygons[i];
  if (geometric.pointInPolygon(pointYouAreTesting, polygon) {
    foundPolygon = polygon;
    break;
  }
}
```

**Comment by svk-man** [comment]
@HarryStevens Thank you very much!
