### ISSUE TITLE
Make lineInterpolate handle values outside of [0; 1]

### ISSUE THREAD

**Issue by yannbriancon** [HarryStevens/geometric#42]
In the library, lines are actually line segments.
Current implementation of lineInterpolate gives an interpolator that returns points outside of the line segment if values passed are outside the interval [0;1].

```js
export function lineInterpolate(line){
  return t => t === 0 ? line[0] : t === 1 ? line[1] : pointTranslate(line[0], lineAngle(line), lineLength(line) * t);
}
```

The following change would allow passing any number value and get the appropriate point on the line segment:
```js
export function lineInterpolate(line){
  return t => t <= 0 ? line[0] : t >= 1 ? line[1] : pointTranslate(line[0], lineAngle(line), lineLength(line) * t);
}
```

**Comment by HarryStevens** [comment]
Changing the function like that would constitute a breaking change, so I'd prefer not to do that. 

However, what if I added a second argument, clamp, a boolean. It would default to false, but if you set it to true, it would restrict the input t to [0, 1]?

**Comment by yannbriancon** [comment]
Thanks for the new parameter 👍
