### ISSUE TITLE
Support for other GeoJSON shapes

### ISSUE THREAD

**Issue by zakjan** [HarryStevens/geometric#5]
Hi, would it be possible to add support for other GeoJSON shapes, especially polygon with holes? Your library is well structured for tree-shaking, so I'm considering to use it in my https://github.com/zakjan/leaflet-lasso.

**Comment by HarryStevens** [comment]
The library is not intended to work with spherical geometry, so I don't think it will be useful for that project. Also, the geometric primitives used by Geometric.js are much simpler than the hierarchical structure of GeoJSON and other geospatial data formats. Still, I do like the idea of supporting polygons with holes. I will look into that. Thanks for the suggestion.
