### ISSUE TITLE
polygonInPolygon -> Accept if PolygonA touches segment of PolygonB

### ISSUE THREAD

**Issue by Mika83AC** [HarryStevens/geometric#8]
Currently I'm trying to use your library to detect if polygons are contained inside another polygon.

But for my case it's also fine if on segments (lines) of the "inside" polygon touches one or more of the "outer" polygon segments (point/line on line case). How can I handle this case with your library? Is there any possibility to do this without breaking the "inside" polygon into single lines and check if they are all inside or on the "outer" polygon segments? 

Best regards,
Michael

**Comment by HarryStevens** [comment]
Can you provide an example? It seems to return true for me: https://observablehq.com/d/a85af90aa1419dd5.

Depending on what you're trying to accomplish, you may also want [polygonIntersectsPolygon](https://github.com/HarryStevens/geometric#polygonIntersectsPolygon).
